import type { ProbeBucket, ProbePayload, ProbeServer } from '../types'

const GB = 1024 ** 3
const TB = 1024 ** 4

function buckets(latency: number, warningAt: number[] = []): ProbeBucket[] {
  return Array.from({ length: 12 }, (_, index) => ({
    ms: latency + ((index * 7) % 11) - 5,
    loss: warningAt.includes(index) ? 0.1 : 0,
  }))
}

function server(input: Partial<ProbeServer> & Pick<ProbeServer, 'name' | 'region'>): ProbeServer {
  return {
    online: true,
    cpu_pct: 8.4,
    mem_used: 1.4 * GB,
    mem_total: 4 * GB,
    disk_used: 12 * GB,
    disk_total: 80 * GB,
    upload_speed: 12 * 1024,
    download_speed: 48 * 1024,
    traffic_used: 220 * GB,
    traffic_limit: 2 * TB,
    os: 'Debian 12',
    expires_at: '2027-08-08',
    renewal_price_cny: 168,
    renewal_cycle: 'year',
    renewal_currency: 'CNY',
    ping: [{ label: '平均', current_ms: 82, loss_pct: 0, buckets: buckets(82) }],
    ...input,
  }
}

export const mockPayload: ProbePayload = {
  enabled: true,
  title: 'Utopia Probe',
  appearance: { theme: 'flat', color_mode: 'light' },
  servers: [
    server({
      name: '🇺🇸 RFC-JP-CO-Clawless',
      region: '日本 · 东京',
      region_country: 'JP',
      cpu_pct: 0.4,
      mem_used: 0.58 * GB,
      disk_used: 13.8 * GB,
      traffic_used: 213 * GB,
      traffic_limit: 3 * TB,
      download_speed: 5 * 1024,
      upload_speed: 5 * 1024,
      expires_at: '2027-07-11',
      renewal_price_cny: 486.53,
      renewal_price: 71.99,
      renewal_currency: 'USD',
      ping: [{ label: '平均', current_ms: 83, loss_pct: 0.1, buckets: buckets(83, [9]) }],
    }),
    server({
      name: '🇯🇵 RFC-JP-CO-Lite',
      region: '日本 · 大阪',
      region_country: 'JP',
      cpu_pct: 0.4,
      mem_used: 1.65 * GB,
      disk_used: 15.4 * GB,
      traffic_used: 171 * GB,
      traffic_limit: 1000 * GB,
      download_speed: 12 * 1024,
      upload_speed: 12 * 1024,
      expires_at: '2026-09-07',
      renewal_price_cny: 30.29,
      renewal_price: 4.49,
      renewal_currency: 'USD',
      renewal_cycle: 'month',
      ping: [{ label: '平均', current_ms: 77, loss_pct: 0.1, buckets: buckets(77, [4, 8]) }],
    }),
    server({
      name: '🇺🇸 VMISS-US',
      region: '美国 · 洛杉矶',
      region_country: 'US',
      cpu_pct: 0.2,
      mem_used: 2.47 * GB,
      disk_used: 22.5 * GB,
      traffic_used: 44 * GB,
      traffic_limit: 500 * GB,
      download_speed: 2 * 1024,
      upload_speed: 883,
      expires_at: '2026-08-23',
      renewal_price_cny: 21.62,
      renewal_price: 4.5,
      renewal_currency: 'CAD',
      renewal_cycle: 'month',
      ping: [{ label: '平均', current_ms: 133, loss_pct: 0, buckets: buckets(133) }],
    }),
    server({
      name: '🇩🇪 Hetzner-DE',
      region: '德国 · 法兰克福',
      region_country: 'DE',
      cpu_pct: 22.8,
      mem_used: 5.8 * GB,
      mem_total: 8 * GB,
      disk_used: 62 * GB,
      disk_total: 160 * GB,
      download_speed: 8.2 * 1024 ** 2,
      upload_speed: 2.1 * 1024 ** 2,
      traffic_used: 7.3 * TB,
      traffic_limit: 20 * TB,
      ping: [{ label: '平均', current_ms: 168, loss_pct: 0.3, buckets: buckets(168, [5, 10]) }],
    }),
    server({
      name: '🇸🇬 SG-Edge',
      region: '新加坡',
      region_country: 'SG',
      cpu_pct: 0,
      mem_used: 2.1 * GB,
      disk_used: 24 * GB,
      download_speed: 0,
      upload_speed: 0,
      online: false,
      expires_at: '2026-07-30',
      ping: [{ label: '平均', current_ms: -1, loss_pct: 100, buckets: Array.from({ length: 12 }, () => ({ ms: -1, loss: 100 })) }],
    }),
    server({
      name: '🇭🇰 HK-Premium',
      region: '中国香港',
      region_country: 'HK',
      cpu_pct: 14.2,
      mem_used: 1.9 * GB,
      disk_used: 31 * GB,
      download_speed: 16.8 * 1024 ** 2,
      upload_speed: 5.4 * 1024 ** 2,
      traffic_used: 780 * GB,
      traffic_limit: 2 * TB,
      ping: [
        { label: '电信', current_ms: 42, loss_pct: 0, buckets: buckets(42) },
        { label: '联通', current_ms: 48, loss_pct: 0, buckets: buckets(48) },
        { label: '移动', current_ms: 52, loss_pct: 0.1, buckets: buckets(52, [8]) },
      ],
    }),
  ],
}
